openapi: "3.0.3"
info:
  title: "test_task_02_03_2024 API"
  description: "test_task_02_03_2024 API"
  version: "1.0.0"
servers:
  - url: "https://test_task_02_03_2024"
tags:
  - name: "Authentication"
    description: "Class for authentication operations"
paths:
  /signin:
    post:
      summary: "Sign in with provided credentials"
      description: ""
      operationId: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/SingInResponse"
components:
  schemas:
    SignInRequest:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"
    SingInResponse:
      type: "object"
      properties:
        welcomeText:
          type: "string"